version: '3.8'

services:
  dept-monopoly:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    environment:
      # Server Configuration
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3000
      
      # Security Configuration
      - HOST_TOKEN=${HOST_TOKEN}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      
      # Rate Limiting
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-900000}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-100}
      
      # Socket.IO Configuration
      - SOCKET_CONNECTION_TIMEOUT=${SOCKET_CONNECTION_TIMEOUT:-20000}
      - SOCKET_HEARTBEAT_TIMEOUT=${SOCKET_HEARTBEAT_TIMEOUT:-5000}
      - SOCKET_HEARTBEAT_INTERVAL=${SOCKET_HEARTBEAT_INTERVAL:-25000}
    volumes:
      # Mount logs directory for persistence (optional)
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - dept-monopoly-network
    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'

networks:
  dept-monopoly-network:
    driver: bridge